apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: helloaspnetcore 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloaspnetcore 
    spec:
      containers:
        - name: helloaspnetcore 
          image: acrbr.azurecr.io/helloaspnetcore
          ports:
          - containerPort: 80